- name: include vaulted variables
  gather_facts: no
  hosts: trainingUi
  tasks:
    - include_vars: ./vault_vars

- name: install trainingUi
  hosts: trainingUi
  tasks:
    - name: Get running trainingUI processes list from remote host
      ignore_errors: yes
      shell: "ps -few | grep trainingUI | grep -v grep | awk '{print $2}'"
      register: running_processes
    - name: Kill running processes
      ignore_errors: yes
      command: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"
    - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
      with_items: "{{ running_processes.stdout_lines }}"
      ignore_errors: yes

    - name: sync binaries
      ansible.posix.synchronize:
        src: ~/eclipse-workspace/trainingUI/build/install/trainingUI
        dest: ~/trainingUI
        recursive: yes
        delete: yes
        
    - name: make sure there is no old log file
      file:
        path: ~/trainingUI/trainingUI/trainingUi.log
        state: absent

    - name: make sure the users directory exists
      file:
        path: ~/users/
        state: directory

    - name: start trainingUI
      shell: nohup ~/trainingUI/trainingUI/bin/trainingUI ~/tasks/handcrafted ~/tasks/mutRev ~/tasks/understanding ~/tasks/experiment >~/trainingUI/trainingUI/trainingUi.log 2>&1 &
      environment:
        JAVA_HOME: "{{ansible_local.java.general.home}}"
        PATH: "{{ansible_env.PATH}}:{{ansible_local.java.general.home}}"
        JDK_JAVA_OPTIONS: |
          -DtrainingUi.auth.alternatives=github,setAuth0
          -DtrainingUi.auth.settings.github=GitHub,https://github.com/login/oauth/authorize,e2a5802b4fb4398d7d51,{{githubOauthSecret}},https://github.com/login/oauth/access_token,https://api.github.com/user,login
          -DtrainingUi.auth.settings.setAuth0=SET-Auth0,https://set.eu.auth0.com/authorize,h7UeZto4xNXjyKjbUTt8tZARF0MrJuG8,{{auth0OauthSecret}},https://set.eu.auth0.com/oauth/token,https://set.eu.auth0.com/userinfo,nickname

    - name: wait for successful startup
      wait_for:
        path: ~/trainingUI/trainingUI/trainingUi.log
        search_regex: Server up and running
        state: present
        timeout: 60
        

